INITIAL_STRING = ''

TYPE_APPEND = 1
TYPE_DELETE = 2
TYPE_PRINT = 3
TYPE_UNDO = 4
TYPE_UNDO_APPEND = -1
TYPE_UNDO_DELETE = -2

OPERATION_DELIMETER = ' '

OPERATION_COUNT__UPPER_LIMIT = 1000000
APPENDAGE_LENGTH_SUM__UPPER_LIMIT = 1000000
CHAR_DELETE_COUNT_SUM__UPPER_LIMIT = 2000000